config/routes.rb
ProyectoAti::Application.routes.draw do
 
  resources :tareas

  resources :usuarios

  resources :tipos

post 'tipos/create/:id', to: 'tipos#create'
put 'tipos/update/:id', to: 'tipos#update'
delete 'tipos/eliminar/:id', to: 'tipos#destroy'
post 'usuarios/create/:id', to: 'usuarios#create'
post 'usuarios/autentica/:id/:password', to: 'usuarios#autenticar'
post 'usuarios/olvido/:id/:secretQ/:secretA', to: 'usuarios#olvido'
put 'usuarios/edit/:id/:password', to: 'usuarios#editar'
post 'tareas/create/:id', to: 'tareas#create'
get 'tareas/listar/:id_usuario', to: 'tareas#listar'
put 'tareas/edit/:id/:id_usuario', to: 'tareas#actualizar'
delete 'tareas/eliminar/:id/:id_usuario', to: 'tareas#eliminar'
put 'tareas/agendar/:id/:id_usuario/:momento', to: 'tareas#agendar'

get ':controller(/:action(/:id(.:format)))'
post ':controller(/:action(/:id(.:format)))'
root 'login#login'

end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
belongs_to:usuario
belongs_to:tipo
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  before_action :set_tarea, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session
  ActiveRecord::Base.logger = Logger.new(STDOUT)

  # GET /tareas
  # GET /tareas.json
  def index
    @tareas = Tarea.all
    respond_to do |format|
      format.xml { render action: 'lista'}
      format.json { render action: 'index'}
      format.html {render action: 'index'}
    end
  end

  # GET /tareas/1
  # GET /tareas/1.json
  def show
    respond_to do |format|
        format.xml { render action: 'show'}
        format.json { render action: 'show'}
        format.html {render action: 'show'}
    end
  end

  # GET /tareas/new
  def new
    @tarea = Tarea.new
  end

  # GET /tareas/1/edit
  def edit
  end

  # POST /tareas
  # POST /tareas.json
  def create
    @tarea = Tarea.new(tarea_params)
    respond_to do |format|
      if @tarea.save
        format.html { redirect_to @tarea, notice: 'Tarea was successfully created.' }
        format.json { render action: 'creada' }
        format.xml {render action: 'creada'}
      else
        format.html { render action: 'new' }
        format.json { render json: 'error' }
        format.xml {render action: 'error'}
      end
    end
  end


  # PATCH/PUT /tareas/1
  # PATCH/PUT /tareas/1.json
  def update
    respond_to do |format|
      if @tarea.update(tarea_params)
        format.html { redirect_to @tarea, notice: 'Tarea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1
  # DELETE /tareas/1.json
  def destroy
    @tarea.destroy
    respond_to do |format|
      format.html { redirect_to tareas_url }
      format.json { head :no_content }
    end
  end

  def eliminar
    @tarea= Tarea.find(params[:id])
    @user= @tarea.id_usuario
      if @user==params[:id_usuario].to_i
        @tarea.destroy
        respond_to do |format|
          format.html { redirect_to tareas_url }
          format.json { render action: 'eliminada' }
          format.xml { render action: 'eliminada'}
        end
      else
        respond_to do |format|
          format.html { render action: 'noElim'}
          format.json { render action: 'noElim'}
          format.xml { render action: 'noElim'}
        end
      end
  end

  def listar
    @tareas=  Tarea.where(id_usuario:params[:id_usuario])
      #format.html { rendirect_to @tarea, notice: 'Se encontraron tareas.'}
    respond_to do |format|
        format.html { render action: 'index' }
        format.json { render action: 'index'}
        format.xml {render action: 'lista'}
    end
    
  end

  def actualizar
      @tarea= Tarea.find(params[:id])
      @usuario= @tarea.id_usuario
        if @tarea.id_usuario==params[:id_usuario].to_i
          respond_to do |format|
            if @tarea.update(tarea_params)
              format.html { redirect_to @tarea, notice: 'Tarea fue actualizada satisfactoriamente.' }
              format.json { render action: 'actualizada' }
              format.xml {render action: 'actualizada'}
            else
              format.html { render action: 'edit' }
              format.json { render action: 'error'}
              format.xml { render action: 'error'}
            end
          end
        else
            respond_to do |format|
              format.html { render action: 'noElim'}
              format.json { render action: 'noActualizada'}
              format.xml { render action: 'noActualizada'}
            end
        end
  end

  def agendar
    @tarea= Tarea.find(params[:id])
    @usuario=@tarea.id_usuario
    if @usuario==params[:id_usuario].to_i
      @user= Usuario.find(@usuario)
      if params[:momento]=="manana"
        @moment= @user.manana
      else
        if params[:momento]=="tarde"
          @moment= @user.tarde
        else
          if params[:momento]=="noche"
            @moment= @user.noche
          end
        end
      end
       @tarea.horaplan= @moment
       #Fechaplan hay que actualizarla a la del dia de hoy o a la q corresponda
       respond_to do |format|
          format.html { redirect_to @tarea, notice: 'Tarea fue agendada satisfactoriamente'}
          format.json { render action: 'Agendada'}
          format.xml { render action: 'Agendada'}
        end
    else
      respond_to do |format|
        format.html { render action: 'noElim'}
        format.json { render action: 'noAgendada'}
        format.xml { render action: 'noAgendada'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarea
      @tarea = Tarea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarea_params
      params.require(:tarea).permit(:id, :descripcion, :fechaC, :fechaPrim, :fechaplan, :prioridad, :estado, :id_tipoT, :id_usuario, :horaplan)
    end

end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/tareas/_form.html.erb
<%= form_for(@tarea) do |f| %>
  <% if @tarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tarea.errors.count, "error") %> prohibited this tarea from being saved:</h2>

      <ul>
      <% @tarea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :fechaC %><br>
    <%= f.date_select :fechaC %>
  </div>
  <div class="field">
    <%= f.label :fechaPrim %><br>
    <%= f.date_select :fechaPrim %>
  </div>
  <div class="field">
    <%= f.label :fechaplan %><br>
    <%= f.datetime_select :fechaplan %>
  </div>
  <div class="field">
    <%= f.label :prioridad %><br>
    <%= f.text_field :prioridad %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :id_tipoT %><br>
    <%= f.text_field :id_tipoT %>
  </div>
  <div class="field">
    <%= f.label :id_usuario %><br>
    <%= f.text_field :id_usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tareas/edit.html.erb
<h1>Editing tarea</h1>

<%= render 'form' %>

<%= link_to 'Show', @tarea %> |
<%= link_to 'Back', tareas_path %>

app/views/tareas/index.html.erb
<h1>Listing tareas</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Descripcion</th>
      <th>Fechac</th>
      <th>Fechaprim</th>
      <th>Fechaplan</th>
      <th>Prioridad</th>
      <th>Estado</th>
      <th>Id tipot</th>
      <th>Id usuario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tareas.each do |tarea| %>
      <tr>
        <td><%= tarea.id %></td>
        <td><%= tarea.descripcion %></td>
        <td><%= tarea.fechaC %></td>
        <td><%= tarea.fechaPrim %></td>
        <td><%= tarea.fechaplan %></td>
        <td><%= tarea.prioridad %></td>
        <td><%= tarea.estado %></td>
        <td><%= tarea.id_tipoT %></td>
        <td><%= tarea.id_usuario %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tareas/new.html.erb
<h1>New tarea</h1>

<%= render 'form' %>

<%= link_to 'Back', tareas_path %>

app/views/tareas/noElim.html.erb
<h1>No tiene permisos sobre esta tarea</h1>

app/views/tareas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @tarea.id %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tarea.descripcion %>
</p>

<p>
  <strong>Fechac:</strong>
  <%= @tarea.fechaC %>
</p>

<p>
  <strong>Fechaprim:</strong>
  <%= @tarea.fechaPrim %>
</p>

<p>
  <strong>Fechaplan:</strong>
  <%= @tarea.fechaplan %>
</p>

<p>
  <strong>Prioridad:</strong>
  <%= @tarea.prioridad %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @tarea.estado %>
</p>

<p>
  <strong>Id tipot:</strong>
  <%= @tarea.id_tipoT %>
</p>

<p>
  <strong>Id usuario:</strong>
  <%= @tarea.id_usuario %>
</p>

<%= link_to 'Back', tareas_path %>