config/routes.rb
ProyectoAti::Application.routes.draw do
 
  resources :tareas

  resources :usuarios

  resources :tipos

post 'tipos/create/:id', to: 'tipos#create'
put 'tipos/update/:id', to: 'tipos#update'
delete 'tipos/eliminar/:id', to: 'tipos#destroy'
post 'usuarios/create/:id', to: 'usuarios#create'
post 'usuarios/autentica/:id/:password', to: 'usuarios#autenticar'
post 'usuarios/olvido/:id/:secretQ/:secretA', to: 'usuarios#olvido'
put 'usuarios/edit/:id/:password', to: 'usuarios#editar'
post 'tareas/create/:id', to: 'tareas#create'
get 'tareas/listar/:id_usuario', to: 'tareas#listar'
put 'tareas/edit/:id/:id_usuario', to: 'tareas#actualizar'
delete 'tareas/eliminar/:id/:id_usuario', to: 'tareas#eliminar'
put 'tareas/agendar/:id/:id_usuario/:momento', to: 'tareas#agendar'

get ':controller(/:action(/:id(.:format)))'
post ':controller(/:action(/:id(.:format)))'
root 'login#login'

end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]
   skip_before_filter :verify_authenticity_token  

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
    respond_to do |format|
        format.html { render action: 'index' }
        format.json { render action: 'index' }
        format.xml {render action: 'index'}
    end
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
    respond_to do |format|
        format.html { render action: 'show' }
        format.json { render action: 'show' }
        format.xml {render action: 'show'}
    end
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create


    @tipo = Tipo.new(tipo_params)
    
    @tipo.id = nil

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render action: 'creado' }
        format.xml {render action: 'creado'}
      else
        format.html { render action: 'new' }
        format.json { render action: 'error' }
        format.xml {render action: 'error'}
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render action: 'actualizado' }
        format.xml {render action: 'actualizado'}
      else
        format.html { render action: 'edit' }
        format.json { render action: 'error' }
        format.xml {render action: 'error'}
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url }
      format.json { render action: 'eliminado' }
      format.xml {render action: 'eliminado'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:id, :descripcionT)
    end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :descripcionT %><br>
    <%= f.text_field :descripcionT %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/form_edit.html.erb
<%= form_tag ({:controller => "tipos", :action => "update"}, :method => "get") do_%>
    <%= label_tag :id_tipo %><br>
    <%= text_field :id_tipo %>

    <%= label_tag :descripcionT %><br>
    <%= text_field :descripcionT %>

    <%= submit_tag "enviar" %>
<% end %>

app/views/tipos/index.html.erb
<h1>Listing tipos</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Descripciont</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.id %></td>
        <td><%= tipo.descripcionT %></td>
        <td><%= link_to 'Show', tipo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New tipo</h1>

<%= render 'form' %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @tipo.id %>
</p>

<p>
  <strong>Descripciont:</strong>
  <%= @tipo.descripcionT %>
</p>


<%= link_to 'Back', tipos_path %>