config/routes.rb
ProyectoAti::Application.routes.draw do
 
  resources :tareas

  resources :usuarios

  resources :tipos

post 'tipos/create/:id', to: 'tipos#create'
put 'tipos/update/:id', to: 'tipos#update'
delete 'tipos/eliminar/:id', to: 'tipos#destroy'
post 'usuarios/create/:id', to: 'usuarios#create'
post 'usuarios/autentica/:id/:password', to: 'usuarios#autenticar'
post 'usuarios/olvido/:id/:secretQ/:secretA', to: 'usuarios#olvido'
put 'usuarios/edit/:id/:password', to: 'usuarios#editar'
post 'tareas/create/:id', to: 'tareas#create'
get 'tareas/listar/:id_usuario', to: 'tareas#listar'
put 'tareas/edit/:id/:id_usuario', to: 'tareas#actualizar'
delete 'tareas/eliminar/:id/:id_usuario', to: 'tareas#eliminar'
put 'tareas/agendar/:id/:id_usuario/:momento', to: 'tareas#agendar'

get ':controller(/:action(/:id(.:format)))'
post ':controller(/:action(/:id(.:format)))'
root 'login#login'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	def self.md5(clave)
		Digest::MD5.hexdigest("#{clave}")
	end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
 # before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
    respond_to do |format|
          format.html { render action: 'index' }
          format.json { render action: 'index' }
          format.xml {render action: 'index'}
      end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
        respond_to do |format|
          format.html { render action: 'show1' }
          format.json { render action: 'show1' }
          format.xml {render action: 'show1'}
      end
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
   # @usuario = Usuario.new(usuario_params)
   puts "ENTRE AL CREATE"
    @usuario = Usuario.new
    @usuario.cedula = params[:cedula]
    @usuario.nombreU = params[:nombreU]
    @usuario.apellidoU = params[:apellidoU]
    @usuario.email = params[:email]
    @usuario.manana = params[:manana]
    @usuario.tarde = params[:tarde]
    @usuario.noche = params[:noche]
    @usuario.username = params[:username]
    @usuario.password = params[:password]
    @usuario.secretQ = params[:secretQ]
    @usuario.secretA = params[:secretA]
    puts "CREE AL USUARIO"
    
    #@usuario.id = nil 
    #@usuario.manana = nil
    #@usuario.tarde = nil
    #@usuario.noche = nil

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render action: 'creado' }
        format.xml { render action: 'creado'}
      else
        format.html { render action: 'new' }
        format.json { render action: 'error1' }
        format.xml {render action: 'error'}
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end

  def autenticar
    @usuario= Usuario.find(params[:id])
    @contra= @usuario.password
      if @contra==params[:password]
        respond_to do |format|
          format.html { render action: 'show' }
          format.json { render action: 'show' }
          format.xml {render action: 'acept'}
        end
    else
      respond_to do |format|
          format.html { render action: 'error' }
          format.json { render action: 'error' }
          format.xml {render action: 'discart'}
      end
    end
  end

  def olvido
    @usuario= Usuario.find(params[:id])
    @Psecreta= @usuario.secretQ
    @Rsecreta= @usuario.secretA
    if @Psecreta==params[:secretQ] and @Rsecreta==params[:secretA]
      respond_to do |format|
          format.html { render action: 'show' }
          format.json { render action: 'show' }
          format.xml {render action: 'show'}
      end
    else
      respond_to do |format|
          format.html { render action: 'error' }
          format.json { render action: 'error' }
          format.xml {render action: 'discart'}
      end
    end
  end

  def editar
    @usuario= Usuario.find(params[:id])
    @contra= @usuario.password
    if @contra==params[:password]
      respond_to do |format|
        if @usuario.update(usuario_params)
          format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
          format.json { render action: 'actualizado' }
          format.xml { render action: 'actualizado'}
        else
          format.html { render action: 'edit' }
          format.json { render action: 'error1' }
          format.xml {render action: 'error'}
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'noAct' }
        format.json { render action: 'noAct' }
        format.xml {render action: 'noAct'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

   
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :CI %><br>
    <%= f.text_field :CI %>
  </div>
  <div class="field">
    <%= f.label :nombreU %><br>
    <%= f.text_field :nombreU %>
  </div>
  <div class="field">
    <%= f.label :apellidoU %><br>
    <%= f.text_field :apellidoU %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :manana %><br>
    <%= f.text_field :manana %>
  </div>
  <div class="field">
    <%= f.label :tarde %><br>
    <%= f.text_field :tarde %>
  </div>
  <div class="field">
    <%= f.label :noche %><br>
    <%= f.text_field :noche %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :secretQ %><br>
    <%= f.text_field :secretQ %>
  </div>
  <div class="field">
    <%= f.label :secretA %><br>
    <%= f.text_field :secretA %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/error.html.erb
<h1>Datos Incorrectos</h1>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Ci</th>
      <th>Nombreu</th>
      <th>Apellidou</th>
      <th>Email</th>
      <th>Manana</th>
      <th>Tarde</th>
      <th>Noche</th>
      <th>Username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.CI %></td>
        <td><%= usuario.nombreU %></td>
        <td><%= usuario.apellidoU %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.manana %></td>
        <td><%= usuario.tarde %></td>
        <td><%= usuario.noche %></td>
        <td><%= usuario.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @usuario.id %>
</p>

<p>
  <strong>Ci:</strong>
  <%= @usuario.CI %>
</p>

<p>
  <strong>Nombreu:</strong>
  <%= @usuario.nombreU %>
</p>

<p>
  <strong>Apellidou:</strong>
  <%= @usuario.apellidoU %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Manana:</strong>
  <%= @usuario.manana %>
</p>

<p>
  <strong>Tarde:</strong>
  <%= @usuario.tarde %>
</p>

<p>
  <strong>Noche:</strong>
  <%= @usuario.noche %>
</p>

<p>
  <strong>Username:</strong>
  <%= @usuario.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usuario.password %>
</p>

<p>
  <strong>Secretq:</strong>
  <%= @usuario.secretQ %>
</p>

<p>
  <strong>Secreta:</strong>
  <%= @usuario.secretA %>
</p>

<%= link_to 'Back', usuarios_path %>